services:
  job-tracker-app:
    container_name: job-tracker-app
    build: 
      context: ./../
      dockerfile: docker/Dockerfile
    ports:
      - 8050:8050
    environment:
      - USERDB_DATABASE=${USERDB_DATABASE}
      - USERDB_HOST=${USERDB_HOST}
      - USERDB_PORT=${USERDB_PORT}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ./../src:/usr/src/app/src
    restart: unless-stopped

  job-tracker-db:
    container_name: job-tracker-db
    image: mongo:6.0.3
    ports:
      - 27017:27017
    volumes:
      - job-tracker-db:/data/db
    restart: unless-stopped

volumes:
  job-tracker-db:

networks:
  default:
    name: job-tracker-network
